### ISSUE TITLE
Docker筆記 - Chapter 9 Deploying Apps with Docker Compose

### ISSUE THREAD

**Issue by blackdiz** [blackdiz/docker-practice#2]
## 9: Deploying Apps with Docker Compose
現代通常是由多個程式組合在一起, 如前端、後端、資料庫, 通常每個程式會獨立執行在自己的container中, 而Docker Compose就是用以佈署多個container, Docker Stack也是, 兩者差異在於Docker Compose是在**single-engine mode**下佈署和管理container, 而Docker Stack則是在**Swarm mode**

### Compose background
- Docker Compose原為叫Fig的python工具, 後被Docker公司買下後改名為Docker Compose, 但未整合進docker engine中, 故需要另外安裝

### Compose files
- Docker Compose的設定檔可以使用YAML或JSON, 預設的名字是**docker-compose.yml**, 但也可用在執行時用`-f`指定設定檔
- 簡單介紹下列範例檔:
    ```yaml
    version: "3.5"
    services:
      web-fe:
        build: .
        command: python app.py
        ports:
          - target: 5000
            published: 5000
        networks:
           - counter-net
        volumes:
          - type: volume
            source: counter-vol
            target: /code
      redis:
        image: "redis:alpine"
        networks:
          counter-net:

    networks:
      counter-net:

    volumes:
      counter-vol:
    ```
  - `version`: 必要㯗位, 且必須寫在設定檔的第一行, `version`定義這個設定檔使用的格式版本, 但和Docker Compose或Docker Engine的版本無關
  - `service`: 定義所有服務, 範例檔中定義了`web-fe`、`redis`兩個服務, 佈署時會分別建立獨立的container
  - `networks`: 定義container使用的網路, 預設下Docker Compose會建立**bridge network**, 這只能連接同一個host內的container, 但可以用`driver`設定不同種類的network, eg: 
        ```
        networks:
        over-net:
          driver: overlay,
          attachable: true
        ```
會建立名為**over-net**的`overlay` network, 且為`attachable`即可以讓不在network中的container加入
  - `volumes`: 設定建立新的volume
  - `service`下每個服務都會建立自己的container, 名稱即為服務的名稱
    - **web-fe**:
      - `build`: 設定Dockerfile的目錄, `.`表示當前目錄
      - `command`: 指定container要執行的主程式, 如: `python app.py`表示要執行名為`app.py`的Python程式, 所以image內要包含Python和`app.py`, 如果Dockerfile已有設定`EXEC`, 則可以省略, 同時這裡的設定會取代掉Dockerfile裡的`CMD`
      - `ports`: 指定container和host mapping的port, `-target: 5000`表示container的5000 port要mapping到`published: 5000`即host的5000 port
      - `networks`: 設定container要加入的network, network必須是既存的或是定義在`networks`的, 如果要加入的network是`overlay`的, 那它必須設定為`attachable: true`
      - `volumes`: 設定要掛載的volume, `source: counter-vol`表示要掛載名為`counter-vol`的volume到container的`target: /code`即container內的`/code`之下, 指定的volume必須是既存的或是設定在下方`volumes`
    - **redis**:
      - `image`: 指定啟動container時使用的image
      - `networks`: 同樣是設定要加入的network

## Deploying an app with Compose
- `docker-compose up`指令是最常用的指令, 用以啟動一個Compose app(docker-compose.yml定義的多個service合稱為Compose app)。它會建立所有image、network、volume, 並啟動container
- `docker-compose up`預設讀取`docker-compose.yml`或`docker-compose.yaml`檔, 但可以用`-f`指定檔案。同時, 通常會加上`-d`指定在背景執行
- Docker Compose有個變數名為`project`預設為使用的Docker Compose設定檔(eg: `docker-compose.yml`)所在的目錄名, 而建立的image預設名字為`<project>_<service name>`, 例如使用的`docker-compose.yml`在counter-app內, service名稱為web-fe, image名稱便為**counter-app_web-fe**。預設的container名字則為`<project>_<service name>_<instance number>`最後一個數字指image目前啟動的container數
- `docker network ls`列出目前建立的network, Docker Compose預設使用`<project>_<network name>`
- `docker volume ls`列出目前建立的volume, Docker Compose預設使用`<project>_<volume name>`

## Managine an app with Compose
- `docker-compose down`會讀取project的`docker-compose.yml`或`docker-compose.yaml`後停止設定檔中服務, 可以用`-f`指定要讀取的檔案
- `docker-compose down`會停止container、network, 但不會刪除建立的volume, 因為volume內的檔案是用以長期使用的, 同時建立的image也會保留以加快之後的啟動速度
- `docker-compose ps`列出指定設定檔內服務所啟動的container、執行的程式、目前狀態和開啟的port
- `docker-compose top`列出指定設定檔內服務啟動container內的process狀態, 注意PID是指**host**的PID而非container裡的
- `docker-compose stop`停止指定設定檔內服務執行的程式, 但不會刪除container和network
- `docker-compose restart`重新啟動指定設定檔內服務的container
- `docker-compose rm`刪除指定設定檔內的服務的container
- volume和network會在佈署服務前先建立
- 由於在`docker-compose.yml`中將建立的volume `counter-val`掛載到web-fb的`\code`中, 而Dockerfile中則把`app.py`複製到container的`\code`裡, 所以`app.py`其實是複製到`counter-val`中, 如果修改`counter-val`中的檔案會同步反映到web-fe中
