### ISSUE TITLE
Docker 筆記 - Chapter 14 Deploying apps with Docker Stacks

### ISSUE THREAD

**Issue by blackdiz** [blackdiz/docker-practice#8]
## Deploying apps with Docker stacks - The Deep Dive
- Docker service是一組container集合, Docker stack是數個Docker service的集合

### Overview of the sample app
- 以`https://github.com/dockersamples/atsea-sample-shop-app.git`為例, 分析`docker-stack.yml`內的key的作用
 - version: Compose file的格式版本
 - services: 設定這個stack要啟動的Docker service
 - networks: 設定這個stack使用的network
 - secrets: 設定stack用到的金鑰(secret)

### Looking closer at the stack file
- stack file即為Docker Compose file
- 最先建立的是networks, 之後才是secrets和services

#### Networks
- 以下面設定為例:
```
networks:
  front-tier:
  back-tier:
  payment:
    driver: overlay
    driver_opts:
      encrypted: 'yes'
```
- 此設定建立了3個network: front-tier、back-tier、payment, 預設下所有network都是overlay network, 且在control plane上加密
- 在data plane加密大約會損耗10%效能, 但還是依具體環境而定, 要在data plane上加密的設定法有:
  - 在`docker network create`指令後加上`-o encrypted`參數
  - 在stack file的`driver_opts`加上`encrypted: yes`如上面範例的payment設定

#### Secrets
- 以下面設定為例:
```
secrets:
  postgres_password:
    external: true
  staging_token:
    external: true
  revprox_key:
    external: true
  revprox_cert:
    external: true
```
設定了4個secret, 且都有`external: true`, 表示這些secret必須在佈署stack前預先建好
- 如果想在佈署時才透過檔案建立secret, 可以將`external: true`改成`file: <filename>`, 但這樣在host上必須要存有設定中指定的未加密檔案造成安全性問題

### Services
- 每個service都是一組描述service的JSON

#### The reverse_proxy service
```
reverse_proxy:
    image: dockersamples/atseasampleshopapp_reverse_proxy
    ports:
      - "80:80"
      - "443:443"
    secrets:
      - source: revprox_cert
        target: revprox_cert
      - source: revprox_key
        target: revprox_key
    networks:
      - front-tier
```
- image: service設定中唯一必填的key是`image`, 指定此service使用的image, 預設下會從Docker Hub下載。Docker Stack不支援Docker Compose的**builds**, 所有的image都需要預先建好
- ports: `80:80`表示將swarm對外的80 port mapping到內部每個service replica的80 port。所有的port預設都使用**ingress mode**, 表示所有node不管有沒有沒service都可以從指定的port連線。如果要改成**host mode**需要如下設定:
```
ports:
    - target: 80
      published: 80
      mode: hose
```
- secrets: secret會以檔案形式掛載在service replicas內, 在Linux下路徑為`/run/secrets`, 檔名為`target`的值, 如: `target: revprox_cert`則為`/run/secrets/revprox_cert`
- networks: 指定service所有的replicas都會加入的networks, 如果沒有預先建立, Docker會建一個overlay network

#### The database service
```
database:
    image: dockersamples/atsea_db
    environment:
      POSTGRES_USER: gordonuser
      POSTGRES_DB_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB: atsea
    networks:
      - back-tier
    secrets:
      - postgres_password
    deploy:
      placement:
        constraints:
          - 'node.role == worker'
```
- environment: 用以加上環境參數, 以上面範例, 設定了**POSTGRES_USER**、**POSTGRES_DB_PASSWORD_FILE**、**POSTGRES_DB**(以此例而言, 如果將變數用secrets設定會更安全)
- deploy.placement.constraints: 可指定一些條件, service只會佈署在滿足所有條件的node上, 可使用`==`(等於)和`!=`(不等於)做邏輯運算, 條件可設定如:
  - Node ID: `node.id == 2ivku8v2gvtg4`
  - Node hostname: `node.hostname != node-2`
  - Node role: `node.role == manager`
  - 使用者自訂的label: `node.labels.security == high`
  - Docker Engine label: `engine.labels.operatingsystem == ubuntu 14.04`

#### The appserver serivce
```
  appserver:
    image: dockersamples/atsea_app
    networks:
      - front-tier
      - back-tier
      - payment
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        failure_action: rollback
      placement:
        constraints:
          - 'node.role == worker'
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    secrets:
      - postgres_password
```
- services.appserver.deploy.replicas: 設定service的replica個數, 預設值為1, 修改後必須重新佈署stack
- services.appserver.deploy.update_config: 設定在rolling-out update時執行的動作, `parallelism: 2`表示每次更新2個replicas, `failure_action: rollback`指如果更新失敗則會做rollback, rollback時會用上次的service設定啟動replicas, `failure_action`的預設值為`pause`, 表示失敗時會停止剩下的replicas更新, 另外還可設為`continue`, 略過失敗後繼續更新
- services.appserver.deploy.restart-policy: 設定當replicas(即container)關閉時如何重啟, `condition: on-failure`表示當container因non-zero exit code時關閉, `max_attempting: 3`會嘗試重啟3次, `delay: 5s`等待5秒再進行下次重啟, `window: 120s`等候120秒測試重啟是否成功

### visualizer
```
 visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8001:8080"
    stop_grace_period: 1m30s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      update_config:
        failure_action: rollback
      placement:
        constraints:
          - 'node.role == manager
```
- stop_grace_period: 當Docker停止container時會傳送**SIGTERM**給container內的**PID 1**程序, container有10秒可以執行停止程序(䆁放資源等), 當超過10秒時就會被強制關閉, 此設定可以修改等候時間
- volumes: 掛載建好的volums到service replica上, `/var/run/docker.sock:/var/run/docker.sock`將host的`/var/run/docker.sock`掛載到container的`/var/run/docker.sock`上。`/var/run/docker.sock`是Docker daemon的API對外socket, 所以這樣可以讓container直接管理、查詢Docker daemon, 在大部分環境下不該如此設定, 此例是因visualizer service需要能查詢到目前的stack狀態

#### payment_gateway
```
 payment_gateway:
    image: dockersamples/atseasampleshopapp_payment_gateway
    secrets:
      - source: staging_token
        target: payment_token
    networks:
      - payment
    deploy:
      update_config:
        failure_action: rollback
      placement:
        constraints:
          - 'node.role == worker'
          - 'node.labels.pcidss == yes'
```
- deploy.placement.constraints中`node.labels.pcidess == yes`, node lable是在執行`docker node update`時加到swarm node中的, 所以只能在swarm中使用

### Deploying the app
- 建立一個swarm和3個node: mgr-1、wrk-1、wrk-2
- `docker node update --label-add pcidss=yes wrk-1`在wrk-1裡加入`"pcidss": "yes"`的label
- `docker stack deploy -c <docker stack file name> <stack name>`可以佈署stack

### Managing the app
- 管理Docker stack時, 建議做法是修改stack file重新佈署, 如果一下子透過指令更新, 一下子使用stack file,  則會造成設定版本的混亂
- 更新的作法是先修改stack file, 再執行`docker stack deploy  -c <stack file name> <stack name>`
- 執行`docker stack rm <stack name>`會刪除stack, 刪除時只刪除service和network, 但不會刪除secret和volume
